package handler

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"runtime/debug"
	"strings"
	"time"

	"clawbench/internal/ai"
	"clawbench/internal/middleware"
	"clawbench/internal/model"
	"clawbench/internal/service"
	"clawbench/internal/ws"
)

const (
	strBlocks    = "blocks"
	strUser      = "user"
	strAssistant = "assistant"
	strContent   = "content"
	strSessionID = "sessionId"
	strError     = "error"
	strToolUse   = "tool_use"
)

// maxReplayTitleRunes caps the session title derived from a replayed message.
const maxReplayTitleRunes = 50

// machineGeneratedUserPrefixes is the single source of truth for every
// machine-generated header stripMachineGeneratedUserText recognises. A user
// turn starting with any of these is machine text (injected system prompt,
// CLI continuation/compaction header, slash command, local-command caveat,
// attachment header, interruption marker) rather than a human question.
//
// isMachineGeneratedTitle uses the SAME list (truncation-tolerant prefix
// match) so a session title is detected as machine-generated if and only if
// the user turn it was derived from would be stripped. Keep this list and
// stripMachineGeneratedUserText's branches in lockstep — a test
// (TestMachinePrefixesMatchStrip) asserts that every prefix here is stripped.
//
// 本列表是 stripMachineGeneratedUserText 所识别的全部机器生成前缀的唯一真相源。
// 以其中任一开头的用户轮次都是机器文本（注入的系统提示块、CLI 续接/压缩头、
// 斜杠命令、本地命令警示、附件头、中断标记），而非人类提问。
// isMachineGeneratedTitle 用同一份列表做（容忍截断的）前缀匹配，使"标题被判为
// 机器文本"当且仅当"其来源用户轮次会被剥离"。新增机器前缀时，本列表与
// stripMachineGeneratedUserText 的分支必须同步，TestMachinePrefixesMatchStrip
// 会断言每个前缀都能被剥离。
var machineGeneratedUserPrefixes = []string{
	"[System Instructions:",
	"[Below is the conversation history",
	"This session is being continued from a previous conversation",
	"<command-name>/",
	"<local-command",
	"Caveat: The messages below were generated by the user",
	"[Request interrupted",
	"[Current file: ",
	"[Current directory: ",
	"[User uploaded ",
}

// deriveSessionTitleFromReplay picks the acp-load session title from the
// first user-typed message in the replay. Machine-generated headers
// prepended to user turns (see stripMachineGeneratedUserText) are removed
// first: ClawBench-created sessions carry the [System Instructions: ...]
// block (prepended by buildPromptBlocks) at the start of their first user
// turn, so without this stripping every imported ClawBench-origin session
// is titled after the injected system prompt instead of the user's actual
// first message.
//
// This is the backend-agnostic fallback used when no readable transcript is
// available (deriveSessionTitleForAgent falls through to it for non-claude
// backends, and for claude when the transcript lookup fails).
//
// 从重放（ACP replay，即导入时 CLI 实时回传的对话历史）中取第一条人类输入作为
// 标题。注意：重放只含 CLI 当前上下文——会话被压缩后首问已被摘要替换，故压缩
// 会话经此路径会取到后期消息。仅作后端无关的兜底（非 claude 后端、或 claude
// 转录读取失败时由 deriveSessionTitleForAgent 落入）。
func deriveSessionTitleFromReplay(messages []replayMessage) string {
	for _, msg := range messages {
		if msg.role != strUser {
			continue
		}
		text, ok := stripMachineGeneratedUserText(service.ExtractPlainText(msg.content))
		if !ok {
			continue
		}
		title := strings.TrimSpace(text)
		if title == "" {
			continue
		}
		if runes := []rune(title); len(runes) > maxReplayTitleRunes {
			title = string(runes[:maxReplayTitleRunes]) + "..."
		}
		return title
	}
	return ""
}

// stripMachineGeneratedUserText removes the machine-generated headers that
// ClawBench or the CLI prepend to a user turn, returning the human-typed
// remainder. It returns ok=false when the entire turn is machine-generated
// and contains no user content.
//
// 剥离 ClawBench 或 CLI 拼在用户轮次前的机器生成头部，返回人类输入的剩余部分。
// 整轮都是机器文本、无用户内容时返回 ok=false。
//
// Headers whose remainder can still carry user text (stripped, looped):
//   - "[System Instructions: ...]\n\n<rest>" — the injected system prompt
//     prepended by buildPromptBlocks to the first user turn of a connection
//   - "[Current file: ...]\n<rest>" and the other attachment/directory
//     reference headers built by ServeChatMessage
//
// Whole-turn machine markers (no user content at all):
//   - "[Request interrupted ...]" — CLI interruption marker
//   - "[Below is the conversation history ..." — CLI continuation/compact
//     summary. When the auto-compact delimiter "[End of conversation
//     history ...]" is present the user's new message follows it and is
//     kept; without the delimiter the whole turn is machine-generated.
//
// Concrete before → after examples (input user-turn text → returned text):
//
//	"[System Instructions: rules]\n\n如何配置自动备份"        → "如何配置自动备份"
//	"[Current file: /tmp/a.png]\n看看这张图"                  → "看看这张图"
//	"Caveat: ...generated by the user...\n\n某段真实输入"     → "某段真实输入"
//	"[Below is ...history...[End of conversation history...]新问题" → "新问题"
//	"[System Instructions: rules]"(无后续)                    → ok=false(整轮机器)
//	"This session is being continued from..."(压缩头,整轮)     → ok=false(整轮机器)
//	"<command-name>/model</command-name>..."(斜杠命令,整轮)    → ok=false(整轮机器)
//	"怎么导出数据库备份"(纯人话)                              → 原样返回,ok=true
//
// 具体前后对照(输入的用户轮次文本 → 返回的文本):
//
//	上面左列即输入,右列即输出;整轮皆机器文本时返回 ok=false,
//	调用方应跳过该轮继续找下一条用户输入。
func stripMachineGeneratedUserText(text string) (string, bool) {
	const compactEnd = "[End of conversation history. Now answer the user's new question.]"
	for {
		// Headers are matched on trimmed text — machine delimiters are
		// typically followed by blank lines before the next segment.
		text = strings.TrimLeft(text, " \t\n")
		if strings.HasPrefix(text, "[Request interrupted") {
			return "", false
		}
		// CLI-native continuation header. When a session is continued after
		// compaction (or via --continue), the CLI writes a plain-English
		// machine turn — "This session is being continued from a previous
		// conversation that ran out of context. ..." — carrying the summary.
		// The user's new question arrives in the NEXT turn, so the whole
		// turn is skipped. This appears both in ACP replays and at the head
		// of transcripts created by --continue.
		if strings.HasPrefix(text, "This session is being continued from a previous conversation") {
			return "", false
		}
		// Slash-command invocations are expanded machine turns, not questions.
		if strings.HasPrefix(text, "<command-name>/") || strings.HasPrefix(text, "<local-command") {
			return "", false
		}
		// "Caveat: The messages below were generated by the user while
		// running local commands. ..." wraps locally-executed command output.
		// Strip the caveat paragraph; any user text after it is kept.
		if strings.HasPrefix(text, "Caveat: The messages below were generated by the user") {
			idx := strings.Index(text, "\n\n")
			if idx < 0 {
				return "", false
			}
			text = text[idx+2:]
			continue
		}
		if strings.HasPrefix(text, "[Below is the conversation history") {
			idx := strings.Index(text, compactEnd)
			if idx < 0 {
				return "", false
			}
			text = text[idx+len(compactEnd):]
			continue
		}
		if strings.HasPrefix(text, "[System Instructions:") {
			idx := strings.Index(text, "]\n\n")
			if idx < 0 {
				return "", false // malformed block without terminator
			}
			text = text[idx+3:]
			continue
		}
		stripped := false
		for _, marker := range []string{
			"[Current file: ",
			"[Current directory: ",
			"[User uploaded ",
		} {
			if !strings.HasPrefix(text, marker) {
				continue
			}
			nl := strings.IndexByte(text, '\n')
			if nl < 0 {
				return "", false // header without any user text line
			}
			text = text[nl+1:]
			stripped = true
			break
		}
		if !stripped {
			return text, true
		}
	}
}

// getOrCreateConnForLoadFn is the function signature for obtaining an ACP
// connection for loading a session. Used to allow test overrides.
type getOrCreateConnForLoadFn func(ctx context.Context, agent *model.Agent, clawbenchSID, acpSessionID, cwd string) (*ai.ACPConn, error)

// getOrCreateConnForLoad is the function used by ServeACPLoadSession to obtain
// an ACP connection for loading a session. Defaults to the real implementation;
// can be overridden in tests.
var getOrCreateConnForLoad getOrCreateConnForLoadFn = defaultGetOrCreateConnForLoad

func defaultGetOrCreateConnForLoad(ctx context.Context, agent *model.Agent, clawbenchSID, acpSessionID, cwd string) (*ai.ACPConn, error) {
	return ai.GetACPConnManager().GetOrCreateConnForLoad(ctx, agent, clawbenchSID, acpSessionID, cwd)
}

// ServeSessionResume handles POST /api/ai/session/resume — restores an archived
// session and returns the session ID. Validates project ownership and session count limits.
func ServeSessionResume(w http.ResponseWriter, r *http.Request) {
	if !requireMethod(w, r, http.MethodPost) {
		return
	}

	projectPath := middleware.GetProjectFromCookie(r)
	if projectPath == "" {
		writeLocalizedError(w, r, model.Forbidden(nil, "NoProjectSelected"))
		return
	}

	var req struct {
		SessionID string `json:"session_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.SessionID == "" {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "SessionIdRequired")
		return
	}

	// Check session exists and belongs to project
	var sessionProjectPath string
	var archived int
	err := service.ReadDB().QueryRowContext(
		r.Context(),
		"SELECT project_path, archived FROM chat_sessions WHERE id = ?",
		req.SessionID,
	).Scan(&sessionProjectPath, &archived)
	if errors.Is(err, sql.ErrNoRows) {
		writeLocalizedErrorf(w, r, http.StatusNotFound, "SessionNotFound")
		return
	}
	if err != nil {
		model.WriteError(w, model.Internal(err))
		return
	}

	// Project isolation
	if sessionProjectPath != projectPath {
		writeLocalizedError(w, r, model.Forbidden(nil, "AccessDenied"))
		return
	}

	// If archived, check session count limit before restoring
	if archived == 1 {
		if model.SessionMaxCount > 0 {
			var count int
			err = service.ReadDB().QueryRowContext(
				r.Context(),
				"SELECT COUNT(*) FROM chat_sessions WHERE project_path = ? AND archived = 0 AND session_type = 'chat'",
				sessionProjectPath,
			).Scan(&count)
			if err != nil {
				model.WriteError(w, model.Internal(err))
				return
			}
			// Restoring an archived session would increase active count by 1
			if count+1 > model.SessionMaxCount {
				writeLocalizedErrorf(w, r, http.StatusConflict, "SessionLimitReached", map[string]any{
					"Count": count,
					"Limit": model.SessionMaxCount,
				})
				return
			}
		}

		// Restore the session
		_, err = service.WriteExecContext(
			r.Context(),
			"UPDATE chat_sessions SET archived = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
			req.SessionID,
		)
		if err != nil {
			model.WriteError(w, model.Internal(fmt.Errorf("failed to restore session %s: %w", req.SessionID, err)))
			return
		}
		slog.Info("session restored from archive",
			slog.String("session", req.SessionID),
			slog.String("project", sessionProjectPath))
	} else {
		slog.Info("session resume requested (already active)",
			slog.String("session", req.SessionID),
			slog.String("project", sessionProjectPath))
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"ok":         true,
		"session_id": req.SessionID,
	})
}

// ServeACPLoadSession handles POST /api/ai/session/acp-load — creates a new ClawBench
// session by loading an existing ACP session via LoadSession. The agent replays the
// full conversation history which is collected and saved to chat_history.
//
//nolint:gocognit,gocyclo // ServeACPLoadSession orchestrates multi-step ACP session loading with replay collection and batch persistence; refactoring would obscure the sequential flow
func ServeACPLoadSession(w http.ResponseWriter, r *http.Request) {
	if !requireMethod(w, r, http.MethodPost) {
		return
	}

	projectPath := middleware.GetProjectFromCookie(r)
	if projectPath == "" {
		writeLocalizedError(w, r, model.Forbidden(nil, "NoProjectSelected"))
		return
	}

	var req struct {
		AgentID      string `json:"agentId"`
		AcpSessionID string `json:"acpSessionId"`
		ProjectID    string `json:"projectId"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.AgentID == "" || req.AcpSessionID == "" {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "InvalidRequestBody")
		return
	}

	// Validate agent exists and supports LoadSession
	configMutex.RLock()
	agent, ok := model.Agents[req.AgentID]
	configMutex.RUnlock()

	if !ok {
		writeLocalizedErrorf(w, r, http.StatusNotFound, "AgentNotFound")
		return
	}

	if !agent.SupportsACP() {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "InvalidRequestBody")
		return
	}

	// Use BackendSpec as authoritative source for LoadSession capability.
	// Some agents (e.g. CodeBuddy) report LoadSession=true in ACP Initialize
	// but don't actually support it.
	spec := model.FindSpecByBackend(agent.Backend)
	if spec == nil || !spec.ACPLoadSession {
		writeLocalizedErrorf(w, r, http.StatusNotImplemented, "NotImplemented")
		return
	}

	// Check if a ClawBench session already exists for this ACP session.
	// source_session_id = "acp:{acpSessionId}" tracks the ACP session origin.
	sourceID := "acp:" + req.AcpSessionID
	var existingID string
	var existingArchived int
	err := service.ReadDB().QueryRow( // r.Context() not easily propagated through ServeACPLoadSession
		"SELECT id, archived FROM chat_sessions WHERE source_session_id = ? AND session_type = 'chat' ORDER BY archived ASC, updated_at DESC LIMIT 1",
		sourceID,
	).Scan(&existingID, &existingArchived)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		slog.Error("handler: failed to check existing ACP session", "error", err)
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	if existingID != "" {
		// A session for this ACP session already exists.
		// Hard-delete the old session and its data so we can recreate
		// it fresh with the latest replay from the ACP agent.
		slog.Info("handler: hard-deleting existing session for ACP reload",
			"old_session", existingID,
			"acp_sid", req.AcpSessionID,
			"was_archived", existingArchived == 1)
		if errHardDel := service.HardDeleteSession(existingID); errHardDel != nil {
			slog.Error("handler: failed to hard-delete existing ACP session", "error", errHardDel)
			writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
			return
		}
	}

	// Create new ClawBench session
	sessionID, err := service.CreateSession(projectPath, agent.Backend, "", req.AgentID, "", "default", "chat")
	if err != nil {
		slog.Error("handler: failed to create session for acp-load", "error", err)
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	// Set SourceSessionID to track the ACP session origin
	if errSrc := service.UpdateSessionSourceID(sessionID, "acp:"+req.AcpSessionID); errSrc != nil {
		slog.Warn("handler: failed to update source_session_id", "session_id", sessionID, "error", errSrc)
	}

	// Also set external_session_id to the loaded ACP session id. Otherwise the
	// session's external_session_id stays empty and a later live send would
	// create a brand-new ACP session (overwriting external_session_id and
	// losing the link to this loaded session), breaking resume/sync of the
	// original conversation.
	if errExt := service.UpdateExternalSessionID(sessionID, req.AcpSessionID); errExt != nil {
		slog.Warn("handler: failed to update external_session_id for acp-load session", "session_id", sessionID, "error", errExt)
	}

	// Set transport to acp-stdio for ACP-loaded sessions
	if errTransport := service.UpdateSessionTransport(sessionID, transportACP); errTransport != nil {
		slog.Warn("handler: failed to update transport for acp-load session", "session_id", sessionID, "error", errTransport)
	}

	// Load ACP session via connection manager
	conn, err := getOrCreateConnForLoad(r.Context(), agent, sessionID, req.AcpSessionID, projectPath)
	if err != nil {
		slog.Error("handler: LoadSession failed", "agent", req.AgentID, "acp_sid", req.AcpSessionID, "error", err)
		// Clean up the session we just created
		_ = service.ArchiveSession(projectPath, agent.Backend, sessionID)
		// Clean up the dead connection from the pool
		ai.GetACPConnManager().CloseConn(sessionID)
		// Detect "Resource not found" from ACP agent — session no longer exists
		if ai.IsACPResourceNotFound(err) {
			writeLocalizedErrorf(w, r, http.StatusNotFound, "ACPSessionNotFound")
			return
		}
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	// Return sessionId immediately so the frontend can switch to the session
	// without waiting for replay processing. The ACP connection is live and
	// the user can send messages even before replay completes — the agent
	// has full context from the loaded session.
	writeJSON(w, http.StatusOK, map[string]any{
		strSessionID:    sessionID,
		"replayPending": true,
	})

	// Spawn async goroutine to replay buffered notifications, persist to DB,
	// and signal completion via WS. This runs after the HTTP response is sent,
	// so long conversations don't block the frontend.
	client := conn.GetClient()
	go func() {
		defer func() {
			if r := recover(); r != nil {
				slog.Error(
					"handler: acp-load replay goroutine panicked",
					slog.String("session_id", sessionID),
					"panic", r,
					"stack", string(debug.Stack()),
				)
				conn.ClearLoadSessionActive()
				// Best-effort: emit replay_done so frontend doesn't hang forever
				ws.EmitToSession(sessionID, ai.StreamEvent{Type: "replay_done"})
			}
		}()

		replayStart := time.Now()

		// Wait for late-arriving SessionUpdate notifications.
		// Some ACP agents replay history via notifications that arrive
		// after the LoadSession RPC response. A short delay ensures
		// these are captured before we read the buffer.
		time.Sleep(500 * time.Millisecond)

		// Clear loadSessionActive BEFORE reading the buffer so that
		// notifications arriving after our read are routed normally
		// (to sessionRoutes → WS) instead of being orphaned in the buffer.
		conn.ClearLoadSessionActive()

		// Read buffered notifications and group into messages (capturing
		// external messageId), then persist. acp-load persists the full replay.
		var messages []replayMessage
		if client != nil {
			messages = groupLoadSessionReplay(client)
		}
		persistReplayMessages(sessionID, projectPath, agent.Backend, messages)

		// Set session title from the first real user-typed message,
		// skipping machine-generated user turns (see
		// deriveSessionTitleFromReplay).
		if title := deriveSessionTitleForAgent(agent, projectPath, req.AcpSessionID, messages); title != "" {
			if err := service.UpdateSessionTitle(sessionID, title); err != nil {
				slog.Warn("handler: failed to set title for acp-load session", "session_id", sessionID, "error", err)
			}
		}

		slog.Info("handler: acp-load replay completed",
			"session_id", sessionID,
			"agent", req.AgentID,
			"acp_sid", req.AcpSessionID,
			"messages", len(messages),
			"elapsed", time.Since(replayStart))

		// Signal replay completion so the frontend can reload history from DB.
		// If no WS subscriber is connected yet (frontend still switching),
		// the event is dropped — the frontend will load from DB on switchSession.
		ws.EmitToSession(sessionID, ai.StreamEvent{Type: "replay_done"})
	}()
}
