package handler

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"runtime/debug"
	"strings"
	"time"

	"clawbench/internal/ai"
	"clawbench/internal/middleware"
	"clawbench/internal/model"
	"clawbench/internal/service"
	"clawbench/internal/ws"
)

const (
	strBlocks    = "blocks"
	strUser      = "user"
	strAssistant = "assistant"
	strContent   = "content"
	strSessionID = "sessionId"
	strError     = "error"
	strToolUse   = "tool_use"
)

// ═════════════════════════════════════════════════════════════════════════════
// MODULE 1 — UNIVERSAL TITLE CLEANING (backend-agnostic, works for EVERY
// agent out of the box). Counterpart: session_title_resolver.go (Module 2,
// per-backend optimization).
//
// What this module does for every backend, with zero backend-specific code:
//
//	deriveSessionTitleFromReplay — takes the first user message from the
//	  ACP LoadSession replay (protocol-uniform; no files read) and strips
//	  machine-generated prefixes to surface the real question.
//	stripMachineText — the data-driven stripper core. Receives rules as
//	  DATA ([]stripRule: prefix + removal strategy), loops trim→match→apply
//	  until human text remains. Never reads files, never names a backend.
//	clientInjectedStripRules — the default rule set: machine headers the
//	  CLIENT prepends to user turns for ALL backends. An unregistered
//	  backend gets exactly these rules and nothing more — no backend's
//	  native rules leak into another backend's path.
//
// 模块一——通用标题清洗(与后端无关,对所有智能体开箱即用)。对应模块见
// session_title_resolver.go(模块二,逐后端优化)。
//   • deriveSessionTitleFromReplay — 取 ACP LoadSession 重放的首条用户消息
//     (协议统一,不读文件),剥机器前缀得到真实首问。
//   • stripMachineText — 数据驱动的剥离器核心。规则以数据传入([]stripRule:
//     前缀+剥离策略),循环"修剪→匹配→套用"直到剩下人类文本。不读文件、
//     不出现任何后端名。
//   • clientInjectedStripRules — 默认规则集:客户端对所有后端注入的机器头。
//     未注册后端恰好拿到这些规则、别无其他——任何后端的原生规则都不会泄入
//     其他后端的路径。
// ═════════════════════════════════════════════════════════════════════════════

// maxReplayTitleRunes caps the session title derived from a replayed message.
const maxReplayTitleRunes = 50

// stripKind enumerates how a machine prefix is removed from a user turn.
//
// 机器前缀从用户轮次中移除的方式。
type stripKind int

const (
	// stripSkipTurn: the WHOLE turn is machine text (e.g. a compaction
	// header, a slash command) — discard it, ok=false.
	// 整轮皆为机器文本(如压缩头、斜杠命令)——丢弃,ok=false。
	stripSkipTurn stripKind = iota
	// stripToDoubleNewline: strip the prefix paragraph (up to "\n\n") and
	// keep scanning the remainder (e.g. a caveat wrapper).
	// 剥到 "\n\n" 为止,保留剩余继续扫(如 Caveat 警示段)。
	stripToDoubleNewline
	// stripToDelimiter: strip up to a fixed end-delimiter and keep scanning
	// (e.g. "[Below is ...[End of conversation history...]<rest>").
	// 剥到固定结束分隔符为止,保留剩余继续扫。
	stripToDelimiter
	// stripToBracketClose: strip a "[...]\n\n" block and keep scanning
	// (e.g. "[System Instructions: ...]\n\n<rest>").
	// 剥掉 "[...]\n\n" 块,保留剩余继续扫。
	stripToBracketClose
	// stripToNewline: strip one line (up to "\n") and keep scanning
	// (e.g. "[Current file: ...]\n<rest>").
	// 剥掉一行(到 "\n"),保留剩余继续扫。
	stripToNewline
)

// stripRule pairs a machine prefix with its removal strategy. Both the
// client-injected (universal) prefixes and each backend's native prefixes
// become stripRules; the stripper itself is backend-agnostic and works off
// a merged slice.
//
// stripRule 把机器前缀与其移除策略配对。客户端注入(通用)前缀与各后端原生前缀
// 都变成 stripRule;剥离器本身与后端无关,只在一个合并切片上工作。
type stripRule struct {
	prefix    string
	kind      stripKind
	delimiter string // only for stripToDelimiter
}

// clientInjectedStripRules are the client (ClawBench) headers prepended to
// user turns for EVERY backend — universal by construction.
//
// 客户端(ClawBench)对所有后端注入的头部——天然通用。
var clientInjectedStripRules = []stripRule{
	{"[System Instructions:", stripToBracketClose, ""},
	{"[Below is the conversation history", stripToDelimiter, "[End of conversation history. Now answer the user's new question.]"},
	{"[Current file: ", stripToNewline, ""},
	{"[Current directory: ", stripToNewline, ""},
	{"[User uploaded ", stripToNewline, ""},
}

// claudeNativeStripRules are the claude-code CLI's own machine headers
// (claudeTranscriptResolver's strip rules). Harmless no-ops for other
// backends (their turns never start with these).
//
// claude-code CLI 自己的机器头(claude 解析器的剥离规则)。对其他后端为无害
// 空转(它们的轮次不会以这些开头)。
var claudeNativeStripRules = []stripRule{
	{"This session is being continued from a previous conversation", stripSkipTurn, ""},
	{"<command-name>/", stripSkipTurn, ""},
	{"<local-command", stripSkipTurn, ""},
	{"Caveat: The messages below were generated by the user", stripToDoubleNewline, ""},
	{"[Request interrupted", stripSkipTurn, ""},
}

// clientInjectedUserPrefixes are the headers the CLIENT (ClawBench) prepends
// to user turns for EVERY backend — derived from clientInjectedStripRules
// so the flat list and the rule list never drift.
//
// 客户端(ClawBench)对所有后端都注入的头部——由 clientInjectedStripRules 推导,
// 扁平列表与规则列表永不失同步。
var clientInjectedUserPrefixes = func() []string {
	prefixes := make([]string, len(clientInjectedStripRules))
	for i, r := range clientInjectedStripRules {
		prefixes[i] = r.prefix
	}
	return prefixes
}()

// claudeNativeUserPrefixes are the claude-code CLI's own machine headers,
// derived from claudeNativeStripRules so the flat list and the rule list
// never drift.
//
// claude-code CLI 自己的机器头——由 claudeNativeStripRules 推导,扁平列表与
// 规则列表永不失同步。
var claudeNativeUserPrefixes = func() []string {
	prefixes := make([]string, len(claudeNativeStripRules))
	for i, r := range claudeNativeStripRules {
		prefixes[i] = r.prefix
	}
	return prefixes
}()

// machineGeneratedUserPrefixes is the combined list used for title
// machine-text DETECTION (isMachineGeneratedTitle): client-injected (all
// backends) + claude-native. The STRIPPER is now data-driven off
// stripRule slices (see stripRulesFor), so this flat list is only for the
// detector's truncation-tolerant prefix match.
//
// 机器文本"检测"所用的合并列表(客户端注入全后端 + claude 原生)。剥离器已改为
// 由 stripRule 切片数据驱动(见 stripRulesFor),此扁平列表仅供检测器的容截断
// 前缀匹配使用。
var machineGeneratedUserPrefixes = append(append([]string{}, clientInjectedUserPrefixes...), claudeNativeUserPrefixes...)

// deriveSessionTitleFromReplay picks the acp-load session title from the
// first user-typed message in the replay. Machine-generated headers are
// stripped with the rule set for the given backend: universal
// client-injected rules always, plus that backend's native rules via its
// resolver. A nil resolver (backend not registered) uses universal rules
// ONLY — no backend's native rules leak into another backend's path.
//
// This is the backend-agnostic fallback used when no readable transcript is
// available (deriveSessionTitleForAgent falls through to it for non-claude
// backends, and for claude when the transcript lookup fails).
//
// 从重放（ACP replay，即导入时 CLI 实时回传的对话历史）中取第一条人类输入作为
// 标题。按给定后端的规则集剥机器前缀:始终含客户端通用注入规则,加上该后端经
// resolver 的原生规则。resolver 为 nil(未注册后端)时只用通用规则——任何后端的
// 原生规则都不会泄入其他后端的路径。
// 注意：重放只含 CLI 当前上下文——会话被压缩后首问已被摘要替换，故压缩
// 会话经此路径会取到后期消息。仅作后端无关的兜底（非 claude 后端、或 claude
// 转录读取失败时由 deriveSessionTitleForAgent 落入）。
func deriveSessionTitleFromReplay(messages []replayMessage, r sessionTranscriptResolver) string {
	rules := stripRulesFor(r)
	for _, msg := range messages {
		if msg.role != strUser {
			continue
		}
		text, ok := stripMachineText(service.ExtractPlainText(msg.content), rules)
		if !ok {
			continue
		}
		title := strings.TrimSpace(text)
		if title == "" {
			continue
		}
		if runes := []rune(title); len(runes) > maxReplayTitleRunes {
			title = string(runes[:maxReplayTitleRunes]) + "..."
		}
		return title
	}
	return ""
}

// stripMachineText is the data-driven stripper core: loop, trim, match a
// rule prefix, apply its strategy; stop at the first non-machine text.
// It receives rules as DATA — the function itself is backend-agnostic and
// never reads files. Concrete before → after examples:
//
//	"[System Instructions: rules]\n\n如何配置自动备份"        → "如何配置自动备份"
//	"[Current file: /tmp/a.png]\n看看这张图"                  → "看看这张图"
//	"[Below is ...[End of conversation history...]新问题"      → "新问题"
//	"This session is being continued..."(整轮,claude规则)     → ok=false
//	"怎么导出数据库备份"(纯人话)                              → 原样返回,ok=true
//
// 数据驱动的剥离器核心:循环、修剪、匹配规则前缀、套用其策略;遇到非机器文本停止。
// 规则以数据传入——函数本身与后端无关、不读任何文件。
func stripMachineText(text string, rules []stripRule) (string, bool) {
	for {
		text = strings.TrimLeft(text, " \t\n")
		matched := false
		for _, r := range rules {
			if !strings.HasPrefix(text, r.prefix) {
				continue
			}
			matched = true
			switch r.kind {
			case stripSkipTurn:
				return "", false
			case stripToDoubleNewline:
				idx := strings.Index(text, "\n\n")
				if idx < 0 {
					return "", false
				}
				text = text[idx+2:]
			case stripToDelimiter:
				idx := strings.Index(text, r.delimiter)
				if idx < 0 {
					return "", false
				}
				text = text[idx+len(r.delimiter):]
			case stripToBracketClose:
				idx := strings.Index(text, "]\n\n")
				if idx < 0 {
					return "", false
				}
				text = text[idx+3:]
			case stripToNewline:
				nl := strings.IndexByte(text, '\n')
				if nl < 0 {
					return "", false
				}
				text = text[nl+1:]
			}
			break // re-loop from the trimmed remainder
		}
		if !matched {
			return text, true
		}
	}
}

// getOrCreateConnForLoadFn is the function signature for obtaining an ACP
// connection for loading a session. Used to allow test overrides.
type getOrCreateConnForLoadFn func(ctx context.Context, agent *model.Agent, clawbenchSID, acpSessionID, cwd string) (*ai.ACPConn, error)

// getOrCreateConnForLoad is the function used by ServeACPLoadSession to obtain
// an ACP connection for loading a session. Defaults to the real implementation;
// can be overridden in tests.
var getOrCreateConnForLoad getOrCreateConnForLoadFn = defaultGetOrCreateConnForLoad

func defaultGetOrCreateConnForLoad(ctx context.Context, agent *model.Agent, clawbenchSID, acpSessionID, cwd string) (*ai.ACPConn, error) {
	return ai.GetACPConnManager().GetOrCreateConnForLoad(ctx, agent, clawbenchSID, acpSessionID, cwd)
}

// ServeSessionResume handles POST /api/ai/session/resume — restores an archived
// session and returns the session ID. Validates project ownership and session count limits.
func ServeSessionResume(w http.ResponseWriter, r *http.Request) {
	if !requireMethod(w, r, http.MethodPost) {
		return
	}

	projectPath := middleware.GetProjectFromCookie(r)
	if projectPath == "" {
		writeLocalizedError(w, r, model.Forbidden(nil, "NoProjectSelected"))
		return
	}

	var req struct {
		SessionID string `json:"session_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.SessionID == "" {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "SessionIdRequired")
		return
	}

	// Check session exists and belongs to project
	var sessionProjectPath string
	var archived int
	err := service.ReadDB().QueryRowContext(
		r.Context(),
		"SELECT project_path, archived FROM chat_sessions WHERE id = ?",
		req.SessionID,
	).Scan(&sessionProjectPath, &archived)
	if errors.Is(err, sql.ErrNoRows) {
		writeLocalizedErrorf(w, r, http.StatusNotFound, "SessionNotFound")
		return
	}
	if err != nil {
		model.WriteError(w, model.Internal(err))
		return
	}

	// Project isolation
	if sessionProjectPath != projectPath {
		writeLocalizedError(w, r, model.Forbidden(nil, "AccessDenied"))
		return
	}

	// If archived, check session count limit before restoring
	if archived == 1 {
		if model.SessionMaxCount > 0 {
			var count int
			err = service.ReadDB().QueryRowContext(
				r.Context(),
				"SELECT COUNT(*) FROM chat_sessions WHERE project_path = ? AND archived = 0 AND session_type = 'chat'",
				sessionProjectPath,
			).Scan(&count)
			if err != nil {
				model.WriteError(w, model.Internal(err))
				return
			}
			// Restoring an archived session would increase active count by 1
			if count+1 > model.SessionMaxCount {
				writeLocalizedErrorf(w, r, http.StatusConflict, "SessionLimitReached", map[string]any{
					"Count": count,
					"Limit": model.SessionMaxCount,
				})
				return
			}
		}

		// Restore the session
		_, err = service.WriteExecContext(
			r.Context(),
			"UPDATE chat_sessions SET archived = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
			req.SessionID,
		)
		if err != nil {
			model.WriteError(w, model.Internal(fmt.Errorf("failed to restore session %s: %w", req.SessionID, err)))
			return
		}
		slog.Info("session restored from archive",
			slog.String("session", req.SessionID),
			slog.String("project", sessionProjectPath))
	} else {
		slog.Info("session resume requested (already active)",
			slog.String("session", req.SessionID),
			slog.String("project", sessionProjectPath))
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"ok":         true,
		"session_id": req.SessionID,
	})
}

// ServeACPLoadSession handles POST /api/ai/session/acp-load — creates a new ClawBench
// session by loading an existing ACP session via LoadSession. The agent replays the
// full conversation history which is collected and saved to chat_history.
//
//nolint:gocognit,gocyclo // ServeACPLoadSession orchestrates multi-step ACP session loading with replay collection and batch persistence; refactoring would obscure the sequential flow
func ServeACPLoadSession(w http.ResponseWriter, r *http.Request) {
	if !requireMethod(w, r, http.MethodPost) {
		return
	}

	projectPath := middleware.GetProjectFromCookie(r)
	if projectPath == "" {
		writeLocalizedError(w, r, model.Forbidden(nil, "NoProjectSelected"))
		return
	}

	var req struct {
		AgentID      string `json:"agentId"`
		AcpSessionID string `json:"acpSessionId"`
		ProjectID    string `json:"projectId"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.AgentID == "" || req.AcpSessionID == "" {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "InvalidRequestBody")
		return
	}

	// Validate agent exists and supports LoadSession
	configMutex.RLock()
	agent, ok := model.Agents[req.AgentID]
	configMutex.RUnlock()

	if !ok {
		writeLocalizedErrorf(w, r, http.StatusNotFound, "AgentNotFound")
		return
	}

	if !agent.SupportsACP() {
		writeLocalizedErrorf(w, r, http.StatusBadRequest, "InvalidRequestBody")
		return
	}

	// Use BackendSpec as authoritative source for LoadSession capability.
	// Some agents (e.g. CodeBuddy) report LoadSession=true in ACP Initialize
	// but don't actually support it.
	spec := model.FindSpecByBackend(agent.Backend)
	if spec == nil || !spec.ACPLoadSession {
		writeLocalizedErrorf(w, r, http.StatusNotImplemented, "NotImplemented")
		return
	}

	// Check if a ClawBench session already exists for this ACP session.
	// source_session_id = "acp:{acpSessionId}" tracks the ACP session origin.
	sourceID := "acp:" + req.AcpSessionID
	var existingID string
	var existingArchived int
	err := service.ReadDB().QueryRow( // r.Context() not easily propagated through ServeACPLoadSession
		"SELECT id, archived FROM chat_sessions WHERE source_session_id = ? AND session_type = 'chat' ORDER BY archived ASC, updated_at DESC LIMIT 1",
		sourceID,
	).Scan(&existingID, &existingArchived)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		slog.Error("handler: failed to check existing ACP session", "error", err)
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	if existingID != "" {
		// A session for this ACP session already exists.
		// Hard-delete the old session and its data so we can recreate
		// it fresh with the latest replay from the ACP agent.
		slog.Info("handler: hard-deleting existing session for ACP reload",
			"old_session", existingID,
			"acp_sid", req.AcpSessionID,
			"was_archived", existingArchived == 1)
		if errHardDel := service.HardDeleteSession(existingID); errHardDel != nil {
			slog.Error("handler: failed to hard-delete existing ACP session", "error", errHardDel)
			writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
			return
		}
	}

	// Create new ClawBench session
	sessionID, err := service.CreateSession(projectPath, agent.Backend, "", req.AgentID, "", "default", "chat")
	if err != nil {
		slog.Error("handler: failed to create session for acp-load", "error", err)
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	// Set SourceSessionID to track the ACP session origin
	if errSrc := service.UpdateSessionSourceID(sessionID, "acp:"+req.AcpSessionID); errSrc != nil {
		slog.Warn("handler: failed to update source_session_id", "session_id", sessionID, "error", errSrc)
	}

	// Also set external_session_id to the loaded ACP session id. Otherwise the
	// session's external_session_id stays empty and a later live send would
	// create a brand-new ACP session (overwriting external_session_id and
	// losing the link to this loaded session), breaking resume/sync of the
	// original conversation.
	if errExt := service.UpdateExternalSessionID(sessionID, req.AcpSessionID); errExt != nil {
		slog.Warn("handler: failed to update external_session_id for acp-load session", "session_id", sessionID, "error", errExt)
	}

	// Set transport to acp-stdio for ACP-loaded sessions
	if errTransport := service.UpdateSessionTransport(sessionID, transportACP); errTransport != nil {
		slog.Warn("handler: failed to update transport for acp-load session", "session_id", sessionID, "error", errTransport)
	}

	// Load ACP session via connection manager
	conn, err := getOrCreateConnForLoad(r.Context(), agent, sessionID, req.AcpSessionID, projectPath)
	if err != nil {
		slog.Error("handler: LoadSession failed", "agent", req.AgentID, "acp_sid", req.AcpSessionID, "error", err)
		// Clean up the session we just created
		_ = service.ArchiveSession(projectPath, agent.Backend, sessionID)
		// Clean up the dead connection from the pool
		ai.GetACPConnManager().CloseConn(sessionID)
		// Detect "Resource not found" from ACP agent — session no longer exists
		if ai.IsACPResourceNotFound(err) {
			writeLocalizedErrorf(w, r, http.StatusNotFound, "ACPSessionNotFound")
			return
		}
		writeLocalizedErrorf(w, r, http.StatusInternalServerError, "InternalError")
		return
	}

	// Return sessionId immediately so the frontend can switch to the session
	// without waiting for replay processing. The ACP connection is live and
	// the user can send messages even before replay completes — the agent
	// has full context from the loaded session.
	writeJSON(w, http.StatusOK, map[string]any{
		strSessionID:    sessionID,
		"replayPending": true,
	})

	// Spawn async goroutine to replay buffered notifications, persist to DB,
	// and signal completion via WS. This runs after the HTTP response is sent,
	// so long conversations don't block the frontend.
	client := conn.GetClient()
	go func() {
		defer func() {
			if r := recover(); r != nil {
				slog.Error(
					"handler: acp-load replay goroutine panicked",
					slog.String("session_id", sessionID),
					"panic", r,
					"stack", string(debug.Stack()),
				)
				conn.ClearLoadSessionActive()
				// Best-effort: emit replay_done so frontend doesn't hang forever
				ws.EmitToSession(sessionID, ai.StreamEvent{Type: "replay_done"})
			}
		}()

		replayStart := time.Now()

		// Wait for late-arriving SessionUpdate notifications.
		// Some ACP agents replay history via notifications that arrive
		// after the LoadSession RPC response. A short delay ensures
		// these are captured before we read the buffer.
		time.Sleep(500 * time.Millisecond)

		// Clear loadSessionActive BEFORE reading the buffer so that
		// notifications arriving after our read are routed normally
		// (to sessionRoutes → WS) instead of being orphaned in the buffer.
		conn.ClearLoadSessionActive()

		// Read buffered notifications and group into messages (capturing
		// external messageId), then persist. acp-load persists the full replay.
		var messages []replayMessage
		if client != nil {
			messages = groupLoadSessionReplay(client)
		}
		persistReplayMessages(sessionID, projectPath, agent.Backend, messages)

		// Set session title from the first real user-typed message,
		// skipping machine-generated user turns (see
		// deriveSessionTitleFromReplay).
		if title := deriveSessionTitleForAgent(agent, projectPath, req.AcpSessionID, messages); title != "" {
			if err := service.UpdateSessionTitle(sessionID, title); err != nil {
				slog.Warn("handler: failed to set title for acp-load session", "session_id", sessionID, "error", err)
			}
		}

		slog.Info("handler: acp-load replay completed",
			"session_id", sessionID,
			"agent", req.AgentID,
			"acp_sid", req.AcpSessionID,
			"messages", len(messages),
			"elapsed", time.Since(replayStart))

		// Signal replay completion so the frontend can reload history from DB.
		// If no WS subscriber is connected yet (frontend still switching),
		// the event is dropped — the frontend will load from DB on switchSession.
		ws.EmitToSession(sessionID, ai.StreamEvent{Type: "replay_done"})
	}()
}
