<template>
  <!-- Fallback for a stale reference: the deep link (or a lingering nav-stack
       entry) can point at an agent that no longer exists — it was deleted, or
       dropped by a rescan. Without this branch the page rendered an empty shell
       (no cards) with only a copy/delete pair, and delete silently no-opped.
       Gated on agentsLoaded so a valid agent does not flash this before the
       list has been fetched. -->
  <div v-if="agentMissing" class="settings-agent-detail settings-agent-detail--missing">
    <UserX :size="32" class="settings-agent-detail__missing-icon" />
    <span class="settings-agent-detail__missing-title">{{ t('settings.items.agentNotFound') }}</span>
    <span class="settings-agent-detail__missing-hint">{{ t('settings.items.agentNotFoundHint') }}</span>
    <button class="fbtn fbtn-primary" @click="emit('back')">
      <ArrowLeft :size="14" />
      <span>{{ t('settings.items.agentBackToList') }}</span>
    </button>
  </div>
  <div v-else class="settings-agent-detail">
    <!-- Custom avatar: a standalone row (the groups above are generated by a
         generic item loop, and SettingsItem has no image control type). -->
    <div class="settings-agent-detail__avatar-row">
      <AgentIcon :backend="agent?.backend || ''" :name="agent?.name" :avatar="agent?.avatar" size="xl" />
      <div class="settings-agent-detail__avatar-text">
        <span class="settings-agent-detail__avatar-label">{{ t('settings.items.agentAvatar') }}</span>
      </div>
      <button class="fbtn settings-agent-detail__avatar-btn" @click="avatarPickerOpen = true">
        {{ t('settings.items.agentAvatarChange') }}
      </button>
    </div>
    <SettingsCard
      v-for="group in groups"
      :key="group.title"
      :title="group.title"
    >
      <SettingsItem
        v-for="item in group.items"
        :key="item.key"
        :label="item.label"
        :description="item.description"
        :type="item.type"
        :model-value="getItemValue(item)"
        :options="item.options"
        :warning="item.warning"
        :force-close="activeKey !== null && activeKey !== item.key"
        @update:model-value="(v: unknown) => handleUpdate(item, v)"
        @edit-toggle="(open: boolean) => handleEditToggle(item.key, open)"
      />
    </SettingsCard>
    <!-- Copy / delete on the same row -->
    <div class="settings-agent-detail__actions">
      <button class="fbtn settings-agent-detail__action-btn" @click="startCopy">
        <Copy :size="16" class="settings-agent-detail__action-icon" />
        <span>{{ t('settings.items.agentCopy') }}</span>
      </button>
      <button class="fbtn fbtn-danger settings-agent-detail__delete-btn" @click="handleDelete">
        <Trash2 :size="16" class="settings-agent-detail__delete-icon" />
        <span>{{ t('settings.items.agentDelete') }}</span>
      </button>
    </div>
    <CopyAgentDialog
      :open="copying"
      :source-name="agent?.name ?? ''"
      :error-message="copyError"
      @close="copying = false"
      @confirmed="handleCopyConfirmed"
    />
    <AgentAvatarPicker
      :open="avatarPickerOpen"
      :agent-name="agent?.name ?? ''"
      @close="avatarPickerOpen = false"
      @saved="handleAvatarSaved"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { ArrowLeft, Copy, Trash2, UserX } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import SettingsItem from './SettingsItem.vue'
import SettingsCard from './SettingsCard.vue'
import CopyAgentDialog from './CopyAgentDialog.vue'
import AgentAvatarPicker from './AgentAvatarPicker.vue'
import AgentIcon from '@/components/common/AgentIcon.vue'
import { useAgents, populateACPStateFromCache } from '@/composables/useAgents'
import { formatModelIdForDisplay } from '@/utils/modelDisplay'
import { patchAgentField } from '@/composables/useSettingsConfig'
import { useToast } from '@/composables/useToast'
import { useDialog } from '@/composables/useDialog'
import '@/assets/modal-footer-btn.css'

const props = defineProps<{
  agentId: string
}>()

const emit = defineEmits<{
  deleted: []
  /** Leave the detail page without deleting anything (stale-reference fallback). */
  back: []
}>()

const { t } = useI18n()
const toast = useToast()
const dialog = useDialog()
const { loadAgents, getAgent, agentsLoaded, updateAgentField, deleteAgent, duplicateAgent, defaultAgentId, setDefaultAgent, getAgentThinkingEffortLevelsIncludingACP } = useAgents()
const activeKey = ref<string | null>(null)
const copying = ref(false)
// Server-side copy failure (e.g. the name is already taken) shown inside the
// dialog; the dialog stays open so the user can pick another name.
const copyError = ref('')
const avatarPickerOpen = ref(false)

onMounted(async () => {
  await loadAgents(true)
  // Merge ACP-reported models into agent.models so the preferred-model selector
  // shows the same stable list as the chat model drawer (Issue #404). Without
  // this, /api/agents now returns the pure CLI list and ACP-only models would
  // be missing when this agent isn't the current session's agent.
  await populateACPStateFromCache(props.agentId)
})

const agent = computed(() => getAgent(props.agentId))

// The requested agent is gone (deleted, or dropped by a rescan). Requiring
// agentsLoaded keeps the first paint of a valid agent from being reported as
// missing — the list starts empty, so before the fetch lands every id is absent.
const agentMissing = computed(() => !agent.value && agentsLoaded.value)

// Determine if agent is ACP-only (has acpCommand but no CLI backend implementation)
const isACPOnly = computed(() => {
  const a = agent.value
  if (!a) return false
  return a.acpCommand && !a.supportsCLI
})

// Determine if agent supports both ACP and CLI (dual transport)
const isDualTransport = computed(() => {
  const a = agent.value
  if (!a) return false
  return a.acpCommand && a.supportsCLI !== false
})

interface AgentItem {
  key: string
  label: string
  description?: string
  type: 'switch' | 'select' | 'number' | 'text' | 'slider' | 'action' | 'info' | 'header' | 'password' | 'textarea'
  options?: { label: string; value: unknown }[]
  warning?: string
  value?: unknown
  patchField?: string
}

const items = computed<AgentItem[]>(() => {
  const a = agent.value
  if (!a) return []

  const result: AgentItem[] = []

  // -- Preference section --
  // Set as Default Agent
  result.push({
    key: 'is_default_agent',
    label: t('settings.items.agentIsDefault'),
    description: t('settings.items.agentIsDefaultDesc'),
    type: 'switch',
  })

  // Preferred Model
  if (a.models && a.models.length > 0) {
    result.push({
      key: 'preferred_model',
      label: t('settings.items.agentPreferredModel'),
      type: 'select',
      options: a.models.map((m: { name: string; id: string }) => ({
        label: m.name || m.id,
        value: m.id,
        modelName: m.name || m.id,
        // CodeBuddy ships models that share a display name (deepseek-v4-pro and
        // deepseek-v4-pro-exclusive are both "Deepseek-V4-Pro"), so the id is
        // the only way to tell them apart in the picker. Some ACP agents carry
        // a JSON-shaped wire id; show it readably (the value stays untouched).
        sublabel: m.name && m.name !== m.id ? formatModelIdForDisplay(m.id) : undefined,
      })),
      patchField: 'preferred_model',
    })
  }

  // Preferred Thinking Effort
  if (a.thinkingEffortLevels && a.thinkingEffortLevels.length > 0) {
    result.push({
      key: 'preferred_thinking_effort',
      label: t('settings.items.agentPreferredThinkingEffort'),
      type: 'select',
      options: a.thinkingEffortLevels.map((l: string) => ({ label: l, value: l })),
      patchField: 'preferred_thinking_effort',
    })
  }

  // Transport (only for dual-transport agents — both ACP and CLI supported)
  if (isDualTransport.value) {
    result.push({
      key: 'transport',
      label: t('settings.items.agentTransport'),
      type: 'select',
      options: [
        { label: 'CLI', value: 'cli' },
        { label: 'ACP-stdio', value: 'acp-stdio' },
      ],
      patchField: 'transport',
    })
  }

  // Preferred Mode (only for ACP agents with available modes)
  if (a.acpCommand && a.acpAvailableModes && a.acpAvailableModes.length > 0) {
    result.push({
      key: 'preferred_mode',
      label: t('settings.items.agentPreferredMode'),
      type: 'select',
      options: a.acpAvailableModes.map((m: { name: string; id: string }) => ({ label: m.name || m.id, value: m.id })),
      patchField: 'preferred_mode',
    })
  }

  // New-session auto-approve default
  result.push({
    key: 'auto_approve',
    label: t('settings.items.agentAutoApprove'),
    description: t('settings.items.agentAutoApproveDesc'),
    type: 'switch',
    patchField: 'auto_approve',
  })

  // -- Identity section --
  result.push({ key: 'header-identity', label: t('settings.items.agentSectionIdentity'), type: 'header' })

  result.push({
    key: 'name',
    label: t('settings.items.agentName'),
    type: 'text',
    patchField: 'name',
  })

  result.push({
    key: 'specialty',
    label: t('settings.items.agentSpecialty'),
    type: 'text',
    patchField: 'specialty',
  })

  // -- Advanced section --
  result.push({ key: 'header-advanced', label: t('settings.items.agentSectionAdvanced'), type: 'header' })

  // System Prompt: editable for CLI/dual agents, read-only info for ACP-only
  if (isACPOnly.value) {
    result.push({
      key: 'custom_system_prompt',
      label: t('settings.items.agentSystemPrompt'),
      description: t('settings.items.agentSystemPromptACPNote'),
      type: 'info',
    })
  } else {
    result.push({
      key: 'custom_system_prompt',
      label: t('settings.items.agentSystemPrompt'),
      description: t('settings.items.agentSystemPromptDesc'),
      type: 'textarea',
      warning: t('settings.items.agentSystemPromptWarning'),
      patchField: 'custom_system_prompt',
    })
  }

  // -- Information section --
  result.push({ key: 'header-info', label: t('settings.items.agentSectionInfo'), type: 'header' })

  result.push({
    key: 'backend',
    label: t('settings.items.agentBackend'),
    type: 'info',
  })

  if (a.command) {
    result.push({
      key: 'command',
      label: t('settings.items.agentCommand'),
      type: 'info',
    })
  }

  const modelCount = a.models?.length ?? 0
  result.push({
    key: 'models_count',
    label: t('settings.items.agentModels'),
    type: 'info',
    value: t('settings.items.agentModelCount', { count: modelCount }),
  })

  if (a.acpCommand) {
    result.push({
      key: 'acp_command',
      label: t('settings.items.agentAcpCommand'),
      type: 'info',
    })
  }

  return result
})

// Group the agent items into cards by header items.
const groups = computed<{ title: string; items: AgentItem[] }[]>(() => {
  const out: { title: string; items: AgentItem[] }[] = []
  let cur: { title: string; items: AgentItem[] } | null = null
  for (const item of items.value) {
    if (item.type === 'header') {
      if (cur) out.push(cur)
      cur = { title: item.label, items: [] }
    } else {
      if (!cur) cur = { title: t('settings.items.agentSectionPreference'), items: [] }
      cur.items.push(item)
    }
  }
  if (cur) out.push(cur)
  return out
})

function getItemValue(item: AgentItem): unknown {
  if (item.type === 'header') return undefined
  if (item.value !== undefined) return item.value

  const a = agent.value
  if (!a) return ''

  switch (item.key) {
    case 'is_default_agent':
      return a.id === defaultAgentId.value
    case 'preferred_model':
      return a.preferredModel || (a.models?.length ? a.models.find((m: { default: boolean }) => m.default)?.id || a.models[0]?.id : '')
    case 'preferred_thinking_effort':
      return a.preferredThinkingEffort || ''
    case 'preferred_mode':
      return a.preferredMode || ''
    case 'transport':
      return a.transport || (a.acpCommand ? 'acp-stdio' : 'cli')
    case 'auto_approve':
      return !!a.autoApprove
    case 'name':
      return a.name || ''
    case 'specialty':
      return a.specialty || ''
    case 'custom_system_prompt':
      // The user's own text is the only prompt value stored; the shared prefix is
      // composed at runtime and never round-trips through the client.
      return a.customSystemPrompt || ''
    case 'backend':
      return a.backend || ''
    case 'command':
      return a.command || ''
    case 'acp_command':
      return a.acpCommand || ''
    default:
      return ''
  }
}

async function handleUpdate(item: AgentItem, value: unknown) {
  // Handle set-as-default toggle
  if (item.key === 'is_default_agent') {
    if (value) {
      try {
        await setDefaultAgent(props.agentId)
      } catch {
        toast.show(t('settings.saveFailed'), { icon: '⚠️', type: 'error', duration: 3000 })
      }
    }
    return
  }

  if (!item.patchField) return

  try {
    await patchAgentField(props.agentId, item.patchField, value as string | number | boolean | null)
    // When changing transport, clear preferred thinking effort if it's no longer valid
    if (item.patchField === 'transport') {
      const newTransport = value as string
      const a = getAgent(props.agentId)
      const currentPref = a?.preferredThinkingEffort || ''
      if (currentPref) {
        const validLevels = newTransport === 'acp-stdio'
          ? getAgentThinkingEffortLevelsIncludingACP(props.agentId)
          : (a?.thinkingEffortLevels || [])
        if (!validLevels.includes(currentPref)) {
          await patchAgentField(props.agentId, 'preferred_thinking_effort', '')
          updateAgentField(props.agentId, 'preferredThinkingEffort', '')
        }
      }
    }
  } catch {
    toast.show(t('settings.saveFailed'), { icon: '⚠️', type: 'error', duration: 3000 })
  }
}

async function handleAvatarSaved(svg: string) {
  try {
    await patchAgentField(props.agentId, 'avatar', svg)
    avatarPickerOpen.value = false
    toast.show(t('settings.items.agentAvatarSaved'), { icon: '✅', duration: 2000 })
  } catch {
    toast.show(t('settings.saveFailed'), { icon: '⚠️', type: 'error', duration: 3000 })
  }
}

function handleEditToggle(key: string, open: boolean) {
  if (open) {
    activeKey.value = key
  } else if (activeKey.value === key) {
    activeKey.value = null
  }
}

function startCopy() {
  copyError.value = ''
  copying.value = true
}

async function handleCopyConfirmed(newName: string) {
  // Clear any previous collision before the new attempt so a repeated failure
  // re-triggers the dialog's error watcher (an unchanged prop would not).
  copyError.value = ''
  try {
    await duplicateAgent(props.agentId, newName)
    copying.value = false
    toast.show(t('settings.items.agentCopied'), { icon: '✅', type: 'success', duration: 3000 })
  } catch (err) {
    // A name collision is recoverable: keep the dialog open and show the
    // reason inline so the user can correct it, instead of a bare toast.
    const msgKey = (err as { msgKey?: string } | null)?.msgKey
    if (msgKey === 'AgentNameTaken') {
      copyError.value = t('settings.items.agentCopyNameTaken')
      return
    }
    copying.value = false
    toast.show(t('settings.items.agentCopyFailed'), { icon: '⚠️', type: 'error', duration: 3000 })
  }
}

async function handleDelete() {
  const a = agent.value
  if (!a) return
  if (a.id === defaultAgentId.value) {
    toast.show(t('settings.items.agentDeleteDefault'), { icon: '⚠️', type: 'error', duration: 3000 })
    return
  }
  const confirmed = await dialog.confirm(
    t('settings.items.agentDeleteConfirm', { name: a.name }),
    { title: t('settings.items.agentDelete'), dangerous: true }
  )
  if (!confirmed) return
  try {
    await deleteAgent(a.id)
    toast.show(t('settings.items.agentDeleted'), { icon: '✅', type: 'success', duration: 3000 })
    emit('deleted')
  } catch {
    toast.show(t('settings.items.agentDeleteFailed'), { icon: '⚠️', type: 'error', duration: 3000 })
  }
}
</script>

<style scoped>
.settings-agent-detail {
  padding: var(--space-4);
  background: var(--bg-secondary);
  min-height: 100%;
}

.settings-agent-detail__avatar-row {
  display: flex;
  align-items: center;
  gap: var(--space-6);
  padding: var(--space-5) var(--space-7);
  margin-bottom: var(--space-4);
  background: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-md);
}

.settings-agent-detail__avatar-text {
  flex: 1;
  min-width: 0;
}

.settings-agent-detail__avatar-label {
  font-size: var(--font-size-md);
  color: var(--text-primary);
}

.settings-agent-detail__avatar-btn {
  flex-shrink: 0;
}

/* Stale-reference fallback: centred block, matching the task panel's missing
   state so a dead link reads as part of the settings surface, not a dead end. */
.settings-agent-detail--missing {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--space-6);
  height: 100%;
  min-height: 100%;
  color: var(--text-muted);
}

.settings-agent-detail__missing-icon {
  color: var(--text-muted);
  opacity: var(--opacity-muted);
}

.settings-agent-detail__missing-title {
  font-size: var(--font-size-lg);
  color: var(--text-muted);
}

.settings-agent-detail__missing-hint {
  font-size: var(--font-size-sm);
  color: var(--text-hint);
  text-align: center;
  max-width: 32em;
}

.settings-agent-detail__actions {
  display: flex;
  gap: var(--space-4);
  margin-bottom: var(--space-4);
}

.settings-agent-detail__action-btn,
.settings-agent-detail__delete-btn {
  flex: 1;
}

.settings-agent-detail__action-icon,
.settings-agent-detail__delete-icon {
  flex-shrink: 0;
}
</style>
